roll back2

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,4 +1,4 @@
-name: ci-cd pipeline 
+name: ci-cd pipeline
 
 on:
   push:
@@ -10,74 +10,78 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: checkcode
+      - name: checkout-code
         uses: actions/checkout@v4
 
-      - name: setup version
+      - name: setup-node
         uses: actions/setup-node@v4
         with:
           node-version: 20
 
-      - name: install dependencies 
+      - name: install-dependencies
         run: npm install
 
-      - name: test build 
-        run: npm test
+      - name: run-tests
+        run: CI=true npm test
 
-       
   build:
     runs-on: ubuntu-latest
     needs: test
 
-
-
     steps:
-      - name: check-code
+      - name: checkout-code
         uses: actions/checkout@v4
 
-      - name: login to dockerhub
+      - name: login-to-dockerhub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOCKEN }}
+          password: ${{ secrets.DOCKER_TOKEN }}
 
-      - name: build image
+      - name: build-image
         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-img:${{ github.sha }} .
 
-      - name: push to docker hub
+      - name: push-image
         run: docker push ${{ secrets.DOCKER_USERNAME }}/node-img:${{ github.sha }}
 
-      - name: login to ec2 
+      - name: deploy-to-ec2
         uses: appleboy/ssh-action@v1
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ubuntu
           key: ${{ secrets.EC2_PEM_KEY }}
           script: |
+
             OLD_IMAGE=$(docker inspect node-app --format='{{.Config.Image}}' 2>/dev/null || true)
-            echo "old image: $OLD_IMAGE"
+
+            echo "Old Image: $OLD_IMAGE"
 
             docker pull ${{ secrets.DOCKER_USERNAME }}/node-img:${{ github.sha }}
+
             docker stop node-app || true
             docker rm node-app || true
-            docker run -d -it -p 3000:3000 --name=node-app ${{ secrets.DOCKER_USERNAME }}/node-img:${{ github.sha }}
+
+            docker run -d -p 3000:3000 \
+              --name node-app \
+              ${{ secrets.DOCKER_USERNAME }}/node-img:${{ github.sha }}
 
             sleep 10
 
-            curl http://localhost:3000/health then,
-             echo " deployment complete"
+            if curl -f http://localhost:3000/health; then
+              echo "Deployment Successful"
             else
-             echo "deployment fail"
+              echo "Deployment Failed"
 
-             docker stop node-app || true
-             docker rm node-app || true 
+              docker stop node-app || true
+              docker rm node-app || true
 
-             if [ ! -z "$OLD_IMAGE" ]; then
-              echo "rolling back"
+              if [ ! -z "$OLD_IMAGE" ]; then
+                echo "Rolling Back"
 
-              docker run -d -p 3000:3000 --name=node-app $OLD_IMAGE
+                docker run -d -p 3000:3000 \
+                  --name node-app \
+                  $OLD_IMAGE
+              fi
 
-            fi
-            exit
-         fi
-            
+              exit 1
+            fi           
